FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Tech.API/Tech.API.csproj", "Tech.API/"]
RUN dotnet restore "Tech/Tech.API.csproj"

COPY . .

WORKDIR "/src/Tech.API"
RUN dotnet build "Tech.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Tech.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Tech.API.dll"]
